version: '3.8'
services:
  api:
    container_name: my-todo-api
#    command: "npm run dev"
    restart: always
    build: .
    ports:
      - '${PORT}:4000'
    depends_on:
      - db
    volumes:
      - .:/usr/app

  db:
    container_name: todo-postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=454612128e6173bf7d4ac3523a04253ad4763fbe1300943917ac19ef49a035d7
      - POSTGRES_DB=degp7j928drcvm

volumes:
  data: {}
